### ISSUE TITLE
Rewrite the Voxel Engine 

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#41]
Issue to keep track of the Voxel rewrite.
#### Changes

| Status | Change | Priority |
| --- | --- | --- |
| finished | Optimize Game Loop | High |
| finished | Deferred Shading | High |
| finished | Singleton  #42 | Medium |
| finished | Change Chunk Rendering | Medium |
| finished | Separate entities rendering of the world rendering | Medium |
| finished | Change Chunk Mesh Creation | Medium |
| finished | Change Physics System | Medium |
| finished | Change Player movement | Medium |
| for next release | glViewport #33 | Medium |
| finished | Change World System | Low |
| finished | Bind Player and Camera in one object | Low |
| finished | New Mod System | Low |

Any other changes or suggestions please write a comment
#### Changelog:

 Build-156 92a0c9e0b127598a6c3f452567b710bd35161817 :
  Changes
@Guerra24: Add ModStateLoop for mods
@Guerra24: Mods are now instanced one time
@Guerra24: New PCF Shadow Mapping

  BugFixes
@Guerra24: Fixed Volumetric Light sun position

 Build-155 70d2f3fbdfb75b5c37d047c467893370ab04dc8b :
  Changes
@Guerra24: Better Parallax Texture
@Guerra24: Add an extra pass to Deferred Shading (Final1)
@Guerra24: NoMoreRabbitPhysics, a new physics movement and speed calculation
@Guerra24: VelocityComponent now uses Vector3f instead of 3 floats

  BugFixes
Display incorrectly setting "Resizable" option.

Build-154 8bd8890b1805155dac4e5fa3471c66d853f938b0 : 
  Changes
@Guerra24: NoMoreStaticDisplay, now display is like any other object
@Guerra24: Display now uses a ContextFormat for OpenGL context
@Guerra24: Display is now a sub-object of Window
@Guerra24: Moved a lot of Display objects to Window object
@Guerra24: Now can create multiple Displays
@Guerra24: Removed a lot of old files

Build 153 f6cc1b64142a0c91ad1580948299288b5fda5729 :
  Changes
@Guerra24: All the assets now are stored in the jar, so the external assets folder only stores generated data like worlds, configuration, mods, etc
@Guerra24: Some changes to Sound System code

  BugFixes
@Guerra24: Quick fix to Parallax Mapping not compiling in non NVIDIA graphic cards (issue #47)

Build 152-2 547a68a65f496fecee2235a2d06a6df0e8d61288 :
@Guerra24: Removed Deprecated Objects
@Guerra24: Better Block Face Culling.

Notes:
GUI Renderer, TextHandler and any OpenGL text system where replaced by NanoVG Rendering System.
Blocks now has a "isTransparent" boolean to check face culling.

 Build 152-1 9bd9a2b5f6460044708fefbbb98b70247b1a5dfc :
Changes
@Guerra24: Reduced effect of parallax mapping.
@Guerra24: Testing wet surface in blocks.
@Guerra24: Add JavaDoc task to build.gradle.
@Guerra24: Player velocity now are clamped to 2.
@Guerra24: Ice now has lower velocity reduction.
@Guerra24: Entities now slide on ice.

BugFixes
@Guerra24: Fixed JUnit Tests.
@Guerra24: Fixed game settings not saving the correct version of the file.
@Guerra24: Fixed player unable to jump inside water or swim.

 Build 151 9a9dc90094ac7dc0010f2c9b7206ce2ed72f2310 :
@danirod: Finally GameResources is a Singleton. Only a single instance of GameResources can exist at the same time in the game (fixes #42)
@danirod: Some multithreading issues related to non-concurrent ArrayLists have been fixed

Build 150 ed094b39d6fd8ffe8ec7f1524b7cfcc29c3e278f :
@Guerra24: More JUnit Test
@Guerra24: Better Debug Screen 

Build 149 2fc72246f676543c4ecbd387d45eeb03f591cc99 :
@Guerra24: Debug Screen In Game

 Build 148 b33425f861f78e03999517d68b222a5abd68e7eb : 
@Guerra24: JUnit test with OpenGL and some changes
@Guerra24: Now shadow is more darker
@Guerra24: GUIRenderer marked as Deprecated
@Guerra24: TextHandler marked as Deprecated

Build 147 49af74ede1fb11df0023b9988e7fdc93fb790e64 : 
@Guerra24: Add Normal Mapping
@Guerra24: Parallax Mapping support
@Guerra24: New options

Build 146 4e00e8c4f9d21968883e051ada3eb96e14d85426 : 
@Guerra24: Removed NitroNet
@Guerra24: New World Selection Screen (WIP) 

Build 145:
@Guerra24: Fixed Friction Based Physics 168e41a09ae96c1fde943bc10770095502bde2a1
@Guerra24: New HDR b3c576b2ee56fd822280a9e831fb1b04ef8ab09b
@Guerra24: Color Correction b3c576b2ee56fd822280a9e831fb1b04ef8ab09b

Build 144 6f265e033efc44c163db508c5053324321e228a8 :
@Guerra24: Better Glow
@Guerra24: Updated Year in License. 

Build 143 8a8dc2ec89f7d2bc40c160a62b0b063049a19b8f :
@Guerra24: Particle rendering now uses glDrawArraysInstanced
@Guerra24: Fixed bug in GlobalStates in case of setting an already set state.

Build 142 815e7090ba06fcd2a75e57dae1611d316ee0078c :
@Guerra24: New Options Menu Background
@Guerra24: New Slider for Menus
@Guerra24: New Draw Distance Selector
@Guerra24: New Collision and Physics System.

Build 141 01dfcf3b56f45ddb72a5ca57914d02e7abdfb4ec :
@Guerra24: Fixed NanoVG crash #46
@Guerra24: New WebRenderer to Main Menu news
@Guerra24: New Custom Mouse Cursor
@Guerra24: Water now are 4 quads instead of 1
@Guerra24: New Options Menu.

Build 140 b8b66af07eea9567116a2e447cf055811faa7b4d :
@Guerra24: Add Ashley as ECS
@Guerra24: Add Log4J as new logger
@Guerra24: New Velocity Based Physics system
@Guerra24: Fixes in entity rendering.

Build 139:
@Guerra24:  Fixed caves generation 7828a198855aa093b8a8a33f005c95524dfe0067
@Guerra24: Merged more features from Infinity 3f851e5f778b73072558a0c0dcbe43b1e571b26b
@Guerra24: Fixed torch light 3f851e5f778b73072558a0c0dcbe43b1e571b26b
@Guerra24: Fixed Volumetric Light 3f851e5f778b73072558a0c0dcbe43b1e571b26b
@Guerra24: Fixed Options button in pause menu 3f851e5f778b73072558a0c0dcbe43b1e571b26b
@Guerra24: Biomes test in progress c58ac8f830794bb14064f1d9a790ce444a0c29d1
@Guerra24: Add License to a lot of files c58ac8f830794bb14064f1d9a790ce444a0c29d1
@Guerra24: Add options menu In Game c58ac8f830794bb14064f1d9a790ce444a0c29d1

Build 138 f2d4730c4ecc70c536b6eee5b655422bdc70886e :
@Guerra24: Fixed NanoVG Crash
@Guerra24: New Buttons
@Guerra24: Merged features from Infinity

Build 137:
@Guerra24: Add NanoVG Support 5ce0652594bd8db79f15b3eacf0fbdda5d7db786 
@Guerra24: Now water receives shadows 392da722a16ed045ba40d20dfdc1312bec6d0619
@Guerra24: Some Fixes with Occlusion Culling 392da722a16ed045ba40d20dfdc1312bec6d0619
@Guerra24: Fixed Projection Matrix on Tessellator shadow rendering e8fef926a0069754f25ef437734ac104e57e0fdd
@Guerra24: Add Occlusion Culling 375562113eec51aa130a3882fef995e39a4a62d5
@Guerra24: Chunk Sort from distance 375562113eec51aa130a3882fef995e39a4a62d5

Build 136 d5997000ec38b174004fd81efc1c66b53d4c48e1 :
@Guerra24: Particles now supports alpha blending

Build 135:
@Guerra24: Pre Release 1 b81fe1a5442466a7b60b7f1bb3d70c7bb7105122
@Guerra24: Bloom FX b9fee81a79a5df05f8f42caaac52aa73fdf04f94

Build 134 91ff1305bf8235498f030e6c2f86fd263cb7e6a7 :
@Guerra24: New Procedurally Generated Waves

Build 133:
@Guerra24: Add Final pass to Deferred Shading/Lighting 7c9fbe4dc1a06d7307f048dcd9e421e5a84fdaf4
@Guerra24: Fixes in shadows 355e196659d6eb5a6c62213560fa400175834ea8
@Guerra24: Changes to game states 355e196659d6eb5a6c62213560fa400175834ea8
@Guerra24: Changes in Game Settings 355e196659d6eb5a6c62213560fa400175834ea8
@Guerra24: Fixes in main loop 4c88c6dfcfb9ec0202f654f11477b4b2b8727306
@Guerra24: Shadows fully implemented in Tessellator 4c88c6dfcfb9ec0202f654f11477b4b2b8727306
@Guerra24: Updated readme and version bump abda0d81a4901829bdb4175f89aeee0b80bc2ed0

Build 132:
@Guerra24: Block light is now loaded to shaders efede9db20e4b20d8c2d54fb7def00b1e7951f8a
@Guerra24: Tessellator now supports Specular and Screen Space Reflections efede9db20e4b20d8c2d54fb7def00b1e7951f8a
@Guerra24: Possible HDPI Fix efede9db20e4b20d8c2d54fb7def00b1e7951f8a
@Guerra24: Block system re-write b60de24524e12ffa4e672912fe11e4f87317cd75
@Guerra24: Now block textures are only in one file b60de24524e12ffa4e672912fe11e4f87317cd75
@Guerra24: Add Tessellator Texture Atlas System b60de24524e12ffa4e672912fe11e4f87317cd75
@Guerra24: Fixed Tessellator Face Up b60de24524e12ffa4e672912fe11e4f87317cd75
@Guerra24: Now Chunk blocks use Tessellator on all faces b60de24524e12ffa4e672912fe11e4f87317cd75
@Guerra24: Fixed Tessellator vertex instability on large positions 6d8253530888260e6368528e701e4f4987c31e23
@Guerra24: Modding system based on annotations and refletions 4ab209331146ad581b85334fd301cc2ebfbbc190

Build 131 17c3f7e15b88b97890067f812e970d7ab393686d :
@Guerra24: Now runs only in one thread
@Guerra24: TextMasterRenderer are now singleton
@Guerra24: Tessellator default cube are broken in top and bottom face, disabled for now
@Guerra24: Chunk top and bottom blocks face still uses the old fixed object mesh, the other faces uses the new Tessellator dynamic mesh generation
@Guerra24: Fixed Crash in case of data updated in the Tessellator

Build 130 04d9e9a2dc644639473f7cd76c2689871111cccd :
@Guerra24: Tessellator, a dynamic mesh generator 

Build 129:
@Danirod: Gradle: automatically add XstartOnFirstThread argument if is running on OS X #45 
@Guerra24: Now game settings are saved to a file 9ffde84e8a2513d355c9610c80e24342fa4e673c

Build 128 66229ba5a8489de43072f2ea53af9c330b78e8f3 :
@Guerra24: Fixed FOG 
@Guerra24: In case of Shader Syntax Error Throws an IllegalStateException 

Build 127:
@Guerra24: Fixed OpenAL Issue related to latest LWJGL3 Build 1028c39a8dc1777303fdb8eb11ee460cabbdac05
@Guerra24: Fixed Transparency 5d71d44035c7e3214e6ad4190a65d92125de0ec3
@Guerra24: Fixed Sun position in screen space 5d71d44035c7e3214e6ad4190a65d92125de0ec3
@Guerra24: Block Picking working e0416691bb1cc048fdec7e931100cce74e8b9b11
@Guerra24: New gData texture e0416691bb1cc048fdec7e931100cce74e8b9b11
@Guerra24: Fixed Block Light e0416691bb1cc048fdec7e931100cce74e8b9b11
@Guerra24: New Particle System 495d0df36b7f852d35283823b66e335f1815d396

Build 126 9b75642b3d524b37b3f5d79826aea522b822cc2a :
@Guerra24: New Multi-Pass Deferred Shading 
@Guerra24: Started the new Mod System

Build 125:
@Guerra24: New Sun/Moon b23419fc4e8d347dff903841873df961a508ce65
@Guerra24: Add 2D Volumetric Light b23419fc4e8d347dff903841873df961a508ce65
@Guerra24: Removed Unused files b23419fc4e8d347dff903841873df961a508ce65
@Guerra24: Re factor Main Menu and Options Menu b23419fc4e8d347dff903841873df961a508ce65
@Guerra24: Fixed LWJGL Version 297708be2d862655848c024541de91b96726a231
@Guerra24: New Composite pass to Deferred Shading e8e212886d237ab5fceffdf96ce75179f15b0b48

Build 124 b08bd42e1606d319c802e4f5223cba4919f9a15c :
@Guerra24: New Ice Block 
@Guerra24: Better Screen Space Reflections 
@Guerra24: Now BlockID is loaded to shaders 
@Guerra24: New Sun/Moon fully generated in GPU 

Build 123 f346f810e6843e41e53f15a1dd34a31866ea5389 :
@Guerra24: Screen Space Reflections

Build 122 455fd1d48c2bff6329c24d8733f6196d8ba8c41d :
@Guerra24: Fixes in Deferred Shading/Rendering 
@Guerra24: Dof working 

Build 121 05e07cad59d5f7a191e2e26a4fe579187bf136e5 :
@Guerra24: Deferred Shading/Rendering 

Build 120 dc5b5a6 :
@Guerra24: Add Motion Blur and Bloom 

Build 119 437ff86 :
@Guerra24: Slick2d is removed due to new texture loading system 
@Guerra24: LWJGL now is downloaded by Gradle 
@Guerra24: Removed LWJGL Natives 
@Guerra24: Fixed the depth texture in post processing 
@Guerra24: FXDOF modified 

Build 118 ee35740 :
@Guerra24: Disabled HQWater and Shadows in OSX devices 
@Guerra24: Can enable or disable the HQWater, Shadows, FXAA and DOF 

Build 117 009b79f :
@danirod: Fixed Fragment Shader 

Build 116 820e347 :
@danirod: Argument names and autostart 

Build 115 d047043 :
@danirod: Extract logic into States

**Comment by danirod** [comment]
Modified the issue to add tasks lists with [ ] and [x].

**Comment by Guerra24** [comment]
Finally the day is here, Voxel 0.0.9 Alpha development has finished :D. Will be released in the next days.
