### ISSUE TITLE
Singleton

### ISSUE THREAD

**Issue by danirod** [Guerra24/Voxel#42]
GameResources has to be initialized in the preInit loop. It has a lot of things that are accesed via get. Since only one possible instance of those things can be, why not use Singleton instead?
I could already do that but since some people has strong arguments against singleton I wanna ask before heading to that.

**Comment by Guerra24** [comment]
Go ahead, you can do.

**Comment by Guerra24** [comment]
Implemented in 40ab184.

**Comment by Guerra24** [comment]
Due to the intensive use of GameResources as a parameter, not be implemented as Singleton yet.

**Comment by danirod** [comment]
Yup, delayed for now.

EDIT. However, keep the work, I'll recatch later.

**Comment by Guerra24** [comment]
Finally after three months its implemented (partially).
