### ISSUE TITLE
Animal Mechanics

### ISSUE THREAD

**Issue by TheOnlySilverClaw** [Guerra24/Voxel#62]
# How should animals work?

Let's fill this world with some live by adding a bunch of animals.
At this stage of development, we have to figure out how complex the animals should be and what roles they should play.
This issue is for collecting and discussing ideas about animals in general.
## Spawning/Population

What determines where animals show up and how many?
Should they just spawn randomly?
Do they mate by themselves (might cause overpopulation and lag if not handled properly!) or do they rely on player interaction?
Do animals only spawn on chunk generation or can they appear later, too?
## Foodchain

Are animals just decoration or do they provide resources for players?
Do animals require food?
Can they eat grass, fruits, crops, etc.?
Can animals hunt each other?
Can animals attack or defend against players or hostile creatures?
## Functions

What are animals good for? Can they be tamed?
Can they be ridden? Do they require a saddle or special skills?
Can animals assist in combat? Can they wear armour or other upgrades?
Can they pull wagons or carry items?

**Comment by Guerra24** [comment]
## Spawning/Population

The animals will spawn depending of the biome, it will spawn in groups of 3 to 6. They will mate by themselves but with low chance to prevent overpopulation, the player can help with this.
They will appear later (chunks generation works in a specific way that can't allow to appear in generation).

## Foodchain

They will provide resources and don't require food. Animals will hunt each other depending of the type.
The attack or defending against players depends of the status.

## Functions

Depending of the animal it will provide different options, only specific animals can be tamed, specific animals can be ridden and will require at least a saddle, the player can learn skills to make the animal better.
Like before depends of the type of animal.

**Comment by TheOnlySilverClaw** [comment]
Okay, that's a start. Will close until someone has more questions. ;)
