### ISSUE TITLE
Corrupted Textures

### ISSUE THREAD

**Issue by jlitewski** [Guerra24/Voxel#84]
The Textures "LuxVacuos-Logo.png" and "Voxel-Logo.png" apparently are corrupted and cannot be displayed.

**Comment by Guerra24** [comment]
Probably not corrupted, In my system load correctly, Firefox load it from local file and Voxel load with no errors. Updated with a copy from my Dropbox. 
EDIT:
Strange, downloaded from GH and can't open, I think that GH or Git damages it at some point, Mmmm...
EDIT 2:
Will be the EOL related to this?. Git trying to convert EOLs in a binary file when uploading causing this....

**Comment by jlitewski** [comment]
It could be. I didn't think of that... Might need to exclude assets from the EOL to test and confirm

**Comment by Guerra24** [comment]
More strange, the other textures load fine. Blocks:
![blocks](https://raw.githubusercontent.com/Lux-Vacuos/Voxel/develop/assets/src/main/resources/assets/voxel/textures/blocks/blocks.png)
![blocks](https://raw.githubusercontent.com/Lux-Vacuos/Voxel/develop/assets/src/main/resources/assets/voxel/textures/blocks/blocks_normal.png)
These use Unix EOL.

**Comment by jlitewski** [comment]
yea I was just confirming that myself, it's only those two images

**Comment by jlitewski** [comment]
I'm still getting issues as of commit a6bb8ca, what image editing program are you using for those two files?

**Comment by Guerra24** [comment]
The images are rendered in Blender, to reduce file size I open it in paint.net and save again, this reduces file size but nothing more.

**Comment by jlitewski** [comment]
I'm assuming that all the other images are also opened in paint.net as well? Maybe try just exporting the images from blender to png and see if it still happens? Or use GIMP instead of paint.net? This is a really weird issue, and the first time I've ever seen git destroy a file due to line endings

**Comment by Guerra24** [comment]
Yes, exporting directly from blender generates a 4mb~8mb file with 32bit depth, this file can't be loaded in Voxel because only supports 16bit depth. I will test with GIMP and see what happens.

**Comment by jlitewski** [comment]
Well, with the GLFW rewrite, it's easy to modify the depth bits for the pixelbuffer.

**Comment by jlitewski** [comment]
@Guerra24 okay I pushed a quick commit that sets the pixel buffer to 32 bits, see if you can't use that

**Comment by Guerra24** [comment]
I mean, the image loader that converts the file to an OpenGL texture. That loader don't supports 32 bit (color) depth.

**Comment by jlitewski** [comment]
ah, alright. would it be easy to modify it? If not, I know PNGLoader supports 32 bit color depth

**Comment by Guerra24** [comment]
Fixed. Caused by Git when converting EOLs from Windows to Unix.
![Logo](https://raw.githubusercontent.com/Lux-Vacuos/Voxel/develop/assets/src/main/resources/assets/voxel/textures/menu/Voxel-Logo.png)
EDIT: Source [Stackoverflow](https://stackoverflow.com/questions/19411981/images-corrupt-after-git-push)
