### ISSUE TITLE
Keyboard HandleInput

### ISSUE THREAD

**Issue by Guerra24** [Guerra24/Voxel#85]
Writing text in one state and then switching to other breaks the input and can't write anymore.

**Comment by jlitewski** [comment]
What exactly were you doing that caused this? Plus, did you KeyboardHandler.enableTextInput() when you switched to the state that needed input (like [this](https://github.com/Lux-Vacuos/Voxel/blob/develop/client/src/main/java/net/luxvacuos/voxel/client/core/states/SPCreateWorld.java#L51))?

**Comment by Guerra24** [comment]
I written an ip in the Multiplayer state and then switched to the CreateWorld state and can't write text, this happened in both ways. I think that the bug is related to KeyboardHandler.enableTextInput() only called in the constructor, not the start function.

**Comment by jlitewski** [comment]
Commit 516bce3 fixes this issue. Thanks for catching that!
