### ISSUE TITLE
Block Overlayer UI is not working as it should on OSX/macOS

### ISSUE THREAD

**Issue by jlitewski** [Guerra24/Voxel#93]
Everything works as it should on Windows 7 x64 and ArchLinux with Radeon R9 380 GPU.

The Block Overlayer UI is super jumpy on 2015 Macbook Pro and not accurate at all.

**Comment by Guerra24** [comment]
Commit b3885c6d5bb457ed3e6faa877321ba4ec21b4599 and 556856febb44a857bf23cb228b0eb1113ee8a966 "should" fix this issue.
