### ISSUE TITLE
How to launch?

### ISSUE THREAD

**Issue by matyklug18** [Guerra24/Voxel#96]
Please answer this questions, Thanks you!

## Notes?

when i launch it, it wants an account, and the site for creating the account is gone. how do i launch it?

**Comment by Guerra24** [comment]
As you can see this project is kinda dead right now, the website was shutdown a while ago but I didn't expect someone to try it in it's current state. I don't think I will be able to work on this soon as my priorities have change and Java GameDev is something I don't do all the time as I did before.

**Comment by matyklug18** [comment]
btw what is the account for? would i be able to remove the account check without many problems?

**Comment by Guerra24** [comment]
The account originally was for the (planned) multiplayer mode, at the time was only used for the launcher, Edit: also for the forum, (planned) mods page and (planned) official server. If you want to try it just run it from source, this commit 21d283d7c9539c880e8b9950b58d8d53f91852fc as the latest one is broken, run the client's [EngineLoader.java](https://github.com/Lux-Vacuos/Voxel/blob/21d283d7c9539c880e8b9950b58d8d53f91852fc/voxel-client/src/main/java/EngineLoader.java). Just remember to pull all git submodules inside this and the LightEngine ones.
